# Generated by Django 4.0.2 on 2022-04-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='vocab_words',
        ),
        migrations.AddField(
            model_name='list',
            name='reading_level',
            field=models.CharField(default='Beginner', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VocabWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.TextField(max_length=1000)),
                ('example_sentence', models.TextField(max_length=1000)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.list')),
            ],
        ),
    ]
