# Generated by Django 4.0.2 on 2022-04-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='student',
            field=models.ManyToManyField(to='main_app.Student'),
        ),
    ]
