# Generated by Django 4.0.2 on 2022-04-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_list_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='student',
            new_name='students',
        ),
    ]
